language: java
jdk:
  - oraclejdk8

before_install: cd QueComemos

install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true -B -V
script: mvn clean cobertura:check -B -V

notifications:
  email:
   - jaecisneros@gmail.com
   - fer.jjp@gmail.com
   - matiromero.15@gmail.com
   - miguenz.matias@gmail.com
   - aleee.eb@gmail.com
   - franscagnetti@hotmail.com
   - hernan.juri@gmail.com

on_success: change
on_failure: always
