language: java
jdk:
  - oraclejdk8

before_install: cd QueComemos

notifications:
  email:
   - jaecisneros@gmail.com
   - fer.jjp@gmail.com
   - matiromero.15@gmail.com
   - miguenz.matias@gmail.com
   - aleee.eb@gmail.com
   - franscagnetti@hotmail.com
   - hernan.juri@gmail.com
